
version: 2
jobs:
  build_and_test_e2e:
    docker:
      - image: circleci/node:10.15.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Repo Check 1
          command: |
            if [ "$CIRCLE_REPOSITORY_URL" == "git@github.com:blockstack/blockstack-browser.git" ]; then
              export TEST_E2E_GREP=account-creation
              npm install && npm run test-e2e:browserstack
            else
              export TEST_E2E_GREP=account-creation
              npm install && npm run test-e2e:localBuild
              exit 1
            fi
      - store_artifacts:
          path: /tmp/test-errors

workflows:
  version: 2
  build_and_test_e2e_local_or_remote-e2e:
    jobs:
      - build_and_test_e2e
