version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run: npm run prod-webapp

  test-e2e:
    docker:
      - image: circleci/node:jessie-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm install && cd ./test-e2e && npm install
      - run:
          name: Running Tests
          command: |
            npm run test-e2e
      - run:
          name: Repo Check 2
          command: |
              if [ "$CIRCLE_REPOSITORY_URL" == "git@github.com:blockstack/blockstack-browser.git" ]; then
                npm install && cd ./test-e2e && npm install
                npm run test-e2e:browserstack
              else
                npm install
                npm run test-e2e:localBuild
              fi
      - store_artifacts:
          path: /tmp/test-errors
workflows:
  version: 2
  build_and_test_e2e_local_or_remote-e2e:
    jobs:
      - build
      - test-e2e
