version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      # test
      - run: npm run test
      # build
      - run: npm run prod-webapp
  test-e2e:
    docker:
      - image: circleci/node:10.15.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      # test
      - run: npm run test-e2e:browserstack
workflows:
  version: 2
  build_and_test-e2e:
    jobs:
      - build
      - test-e2e